name: Initiative Template
description: File an initiative description.
title: "[Initiative]: "
labels: ["initiative"]
assignees:
  - marcoslal
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this initiative! From the ProdOps team we'll help you to share all of them.

  - type: textarea
    id: whatidea
    attributes:
      label: What is the idea you would like to implement?
      description: Tell us also what do you expect to happen. Mind to explain the expected outcome and the value that brings to your product/team.
      placeholder: Use this text box to describe.
    validations:
      required: true
      
  - type: dropdown
    id: skill
    attributes:
      label: Skills of ProdOps
      multiple: true
      description: What main skills in ProdOps is your initiative gonna need? Select all the ones you think that apply to your initiative.
      options:
        - Communication
        - Delivery
        - Invoincing
        - Software Management
        - UX/UI
    validations:
      required: true
      
      
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: What is the current status of the issue? Leave the field for the team if you're creating the task now.
      options:
        - To be refined
        - Analysis
        - Backlog
        - In Progress
        - Blocked
        - Done
        - Closed
    validations:
      required: false
      
  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Leave the field for the team if you're creating the task now.
      options:
        - NA
        - XS
        - S
        - M
        - L
        - XL
    validations:
      required: false
      

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or phone number
    validations:
      required: false

  - type: input
    id: attachments
    attributes:
      label: Attachments Info
      description: Share links to existing attachments
      placeholder: Links to relevant existing documents.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Conditions
      description: By submitting this issue, you agree to out conditions and process to implement or reject the initiative sugestion in our [ProdOps conditions](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
 
